---
applications:
  - name: api
    instances: 1
    memory: 1.5G
    disk_quota: 1G
    stack: cflinuxfs4
    buildpacks:
      - python_buildpack
    path: ../
    routes:
      - route: fec-feature-api.app.cloud.gov
    services:
      - fec-api-elasticsearch
      - fec-elasticache-redis
      - fec-creds-feature
      - fec-s3-api
      - fec-s3-snapshot
    env:
      APP_NAME: fec | api | feature
